fix golangci-lint warnings
Fix the following issues:

  etcd/etcd.go:39:50: S1002: should omit comparison to bool constant, can be simplified to `match` (gosimple)
  	if match, _ := regexp.Match("0\\.4\\.*", body); match == true {
  etcd/etcd.go:4:2: SA1019: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package [io] or package [os], and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
  	"io/ioutil"
  zookeeper/zookeeper.go:30:11: Error return value of `c.Create` is not checked (errcheck)
  		c.Create(uri.Path, []byte{}, 0, zk.WorldACL(zk.PermAll))
  bridge/bridge.go:229:6: S1002: should omit comparison to bool constant, can be simplified to `!b.config.Internal` (gosimple)
  		if b.config.Internal != true && port.HostPort == "" {
  bridge/bridge.go:301:5: S1002: should omit comparison to bool constant, can be simplified to `b.config.Internal` (gosimple)
  	if b.config.Internal == true {
  bridge/bridge.go:213:41: composites: github.com/fsouza/go-dockerclient.PortBinding struct literal uses unkeyed fields (govet)
  		published := []dockerapi.PortBinding{ {"0.0.0.0", port.Port()}, }